config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # デバイス関連のルーティング
  ##########ここから##########
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  #admins/registrationsは必要？  registrations: 'admins/registrations'
  }

  ##########ここまで##########

  #管理者ページのルーティング
  ##########ここから##########
  namespace :admin do
    #admin/customersコントローラのルーティング
    resources :customers, only: [:index, :show, :edit, :update]

    #admin/productsコントローラのルーティング
    resources :products, only: [:index, :show, :edit, :new, :update, :create]

    #admin/genresコントローラのルーティング
    resources :genres, only: [:index, :edit, :update, :create]

    #admin/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :update] do

      #admin/order_itemsコントローラのルーティング
      resources :order_items, only: [:update]
    end
  end
  ##########ここまで##########

  #会員ページのルーティング
  ##########ここから##########
  scope module: :public do
    #public/homesコントローラのルーティング
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'

    #public/cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete 'cart_items', to: 'cart_items#destroy_all', as: 'destroy_all'


    #public/customersコントローラのルーティング
    get '/customers/mypage', to: 'customers#show', as: 'mypage'
    resource :customers, only: [:edit, :update] do
      collection do
        get 'quit_check'#'/customers/quit_check', to: 'customers#quit_check', as:
        patch 'quit'#'/customers/quit', to: 'customers#quit', as:
      end
    end

    #public/deliveriesコントローラのルーティング
    resources :deliveries, only: [:index, :edit, :update, :destroy]

    #public/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get 'finish'#'/orders/finish', to: 'orders#finish', as:
        post 'confirm'#'/orders/confirm', to: 'orders#confirm', as:
      end
    end

    # public/searchコントローラのルーティング
    get "/customers/search", to: "search#search", as: "search"

  devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  # passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
  }

    #public/productsコントローラのルーティング
    resources :products, only: [:index, :show]
  end
##########ここまで##########
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :deliveries, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  has_many :products, through: :cart_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: {message: 'カタカナで入力して下さい。'}, format: { with: /\A[ｧ-ﾝﾞﾟァ-ヶー－]+\z/ }
  validates :kana_last_name, presence: {message: 'カタカナで入力して下さい。'}, format: { with: /\A[ｧ-ﾝﾞﾟァ-ヶー－]+\z/ }
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number,  presence: true

  # statusに関するenum記述
  # ↓enumではなくてbooleanなのでここに書くとエラーになるのでコメントアウトしました
  # enum is_deleted: { 有効: false, 無効: true }

  # ログインする時に退会済み(is_deleted==true)のユーザーを弾くためのメソッドを作成します。
  # super && (self.is_deleted == false)で、customerのis_deletedがfalseならtrueを返すようにしています。
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  # 会員フルネーム(カナ)
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  #カート内商品小計(税抜き価格)を返すメソッド
  def base_price_subtotal(product_id)
    product = Product.find(product_id)
    cart_item = self.cart_items.find_by(product_id: product_id)
    base_price_total = product.base_price * cart_item.quantity
    return base_price_total
  end

  #カート内商品小計(税込み価格)を返すメソッド
  def subtotal(product_id)
    return (self.base_price_subtotal(product_id) * 1.08)
  end

  # カート内商品合計金額を返すメソッド
  def total
    cart_items = self.cart_items
    #カート内の税抜きの合計金額を繰り返し処理で求める。
    base_price_total = 0
    cart_items.each do |cart_item|
      base_price_total += cart_item.product.base_price * cart_item.quantity
    end
    #税抜きの合計金額に消費税を加える。
    return  (base_price_total * 1.08).floor
  end

  #くまさん追記 / 07/27 14:10
  # カートアイテムでの数字の表示を直すためのもの
  def subtotal2(product_id)
    return (self.base_price_subtotal(product_id) * 1.08).floor.to_s(:delimited, delimiter: ',')
  end

  #くまさん追記 / 07/27 14:10
  # カートアイテムでの数字の表示を直すためのもの
  def total2
    cart_items = self.cart_items
    #カート内の税抜きの合計金額を繰り返し処理で求める。
    base_price_total = 0
    cart_items.each do |cart_item|
      base_price_total += cart_item.product.base_price * cart_item.quantity
    end
    #税抜きの合計金額に消費税を加える。
    return  (base_price_total * 1.08).floor.to_s(:delimited, delimiter: ',')
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    #@customers = Customer.all
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end


private

   def customer_params
     	params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
     	:first_name_kana, :email, :postcode, :address, :phone_number, :is_deleted)
   end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row">
    <div class="col-md-11">
      <h3 class="mt-2"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>
    </div>

  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th style="width:60px"><%= f.label :氏名 %></th>
          <!--d-flexで直下がflexに。横並びになる！-->
          <td class="d-flex">
            <!--form-controlで枠が綺麗になる-->
            <%= f.text_field :last_name, class:"form-control" %>
            <%= f.text_field :first_name, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th class="text-nowrap"><%= f.label :フリガナ %></th>
          <td class="d-flex">
            <%= f.text_field :last_name_kana, class:"form-control" %>
            <%= f.text_field :first_name_kana, class:"form-control" %>
          </td>
        </tr>
        <tr>
          <th><%= f.label :郵便番号 %></th>
          <td><%= f.text_field :postcode, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :住所 %></th>
          <td><%= f.text_field :address, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :電話番号 %></th>
          <td><%= f.text_field :phone_number, class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :メールアドレス %></th>
          <td><%= f.text_field :email , class:"form-control"%></td>
        </tr>
      </div>
    </div>


    <div class="row">
      <div class="col-md-8">
        <!--form-inlineで横並びにする　flex-nowrapで折り返しなし-->
        <tr class="form-group form-inline flex-nowrap">
          <th class="form-group mr-3">会員ステータス</th>
          <td class="form-group">
          　<%= f.radio_button :is_deleted, :false %>
          　<%= f.label :is_deleted, "有効", value: :false %>
          　<%= f.radio_button :is_deleted, :true %>
          　<%= f.label :is_active, "退会", value: :true %>
          </td>
        </tr>
        <tr>
          <td>
          <%= f.submit "変更を保存", class: "btn btn-secondary" %>
          <% end %>
          </td>
        </tr>

    </table>
  </div>
</div>





</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row">
        <div>
          <h2>会員一覧</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-10 mx-auto">
          <table class="table table-bordered">
            <thead class="thead-light">
              <th>
                <p>会員ID</p>
              </th>
              <th>
                <p>氏名</p>
              </th>
              <th>
                <p>メールアドレス</p>
              </th>
              <th>
                <p>ステータス</p>
              </th>
            </thead>
            <tbody>
              <% @customers.each do |customer| %>
                <tr>
                  <td>
                    <p>
                      <%= customer.id %>
                    </p>
                  </td>
                  <td>
                    <p>
                      <%= link_to admin_customer_path(customer.id) do %>
                        <%= customer.last_name %><%= customer.first_name %>
                      <% end %>
                    </p>
                  </td>
                  <td>
                    <p>
                      <%= customer.email %>
                    </p>
                  </td>
                  <td>
                    <% if customer.is_deleted == false %>
                     <p class="text-success">有効</p>
                    <% else %>
                     <p class="text-danger">退会</p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class="mt-4"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  <div class="row mt-4">
    <div class="col-2">
      <p>会員ID</p>
      <p>氏名</p>
      <p>フリガナ</p>
      <p>郵便番号</p>
      <p>住所</p>
      <p>電話番号</p>
      <p>メールアドレス</p>
      <p>会員ステータス</p>
    </div>
    <div class="col-10">
      <p><%= @customer.id %></p>
      <p><%= @customer.last_name %> <%= @customer.first_name %></p>
      <p><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></p>
      <p><%= @customer.postcode %></p>
      <p><%= @customer.address %></p>
      <p><%= @customer.phone_number %></p>
      <p><%= @customer.email%></p>
      <% if @customer.is_deleted == false %>
      <p class="text-success">有効</p>
      <% else %>
      <p>退会</p>
      <% end %>
    </div>
    <div class="col-8 mx-auto">
      <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-sm btn-info mx-3" %>
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-sm btn-success mx-3" %>
    </div>
  </div>
</div>