config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # デバイス関連のルーティング
  ##########ここから##########
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  #admins/registrationsは必要？  registrations: 'admins/registrations'
  }

  ##########ここまで##########

  #管理者ページのルーティング
  ##########ここから##########
  namespace :admin do
    #admin/customersコントローラのルーティング
    resources :customers, only: [:index, :show, :edit, :update]

    #admin/productsコントローラのルーティング
    resources :products, only: [:index, :show, :edit, :new, :update, :create]

    #admin/genresコントローラのルーティング
    resources :genres, only: [:index, :edit, :update, :create]

    #admin/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :update] do

      #admin/order_itemsコントローラのルーティング
      resources :order_items, only: [:update]
    end
  end
  ##########ここまで##########

  #会員ページのルーティング
  ##########ここから##########
  scope module: :public do
    #public/homesコントローラのルーティング
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'

    #public/cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete 'cart_items', to: 'cart_items#destroy_all', as: 'destroy_all'


    #public/customersコントローラのルーティング
    get '/customers/mypage', to: 'customers#show', as: 'mypage'
    resource :customers, only: [:edit, :update] do
      collection do
        get 'quit_check'#'/customers/quit_check', to: 'customers#quit_check', as:
        patch 'quit'#'/customers/quit', to: 'customers#quit', as:
      end
    end

    #public/deliveriesコントローラのルーティング
    resources :deliveries, only: [:index, :edit, :update, :destroy]

    #public/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get 'finish'#'/orders/finish', to: 'orders#finish', as:
        post 'confirm'#'/orders/confirm', to: 'orders#confirm', as:
      end
    end

    # public/searchコントローラのルーティング
    get "/customers/search", to: "search#search", as: "search"

  devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  # passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
  }

    #public/productsコントローラのルーティング
    resources :products, only: [:index, :show]
  end
##########ここまで##########
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :postage, presence: true
  validates :billing_total, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true

  # 支払方法に関するenum記述
  enum payment_method: { 銀行振込: 0, クレジットカード: 1 }

  # statusに関するenum記述
    enum status: {
    入金待ち:0,
    入金確認中:1,
    製作中:2,
    発送準備中:3,
    発送済み:4
  }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def show
    @order = Order.find(params[:id])

    # [目的] f.selectで用いる選択肢を作る。
    #配列をつくるために、Arrayクラスのインスタンスを生成する
    @array_order_status = Array.new
    # 配列の要素を追加する
    @array_order_status.push(["入金待ち", 0], ["入金確認中", 1], ["製作中",2], ["発送準備中", 3],["発送済み", 4])

    # [目的] f.selectで用いる選択肢を作る。
    #配列をつくるために、Arrayクラスのインスタンスを生成する
    @array_order_item_making_status = Array.new
    # 配列の要素を追加する
    @array_order_item_making_status.push(["着手不可", 0], ["製作待ち", 1], ["製作中", 2], ["製作完了", 3])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(status: params[:order][:status].to_i)
      # [目的]statusが1の場合、すべてのレコードのmaking_statusを1にする。
      if Order.statuses[@order.status] == 1
        @order.order_items.each do |order_item|
          order_item.update(making_status: 1)
        end
      end
      flash[:success] = "注文ステータスを更新しました"
      redirect_to request.referer
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :name,
      :postcode,
      :address,
      :postage,
      :billing_total,
      :payment_method,
      :status
      )
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h3>注文履歴一覧</h3>
    </div>
  </div>
  <div>
    <div class="col-10 mx-auto">
    <!--ここからテーブル箇所-->
      <table class="table">
        <thead class="thead-light">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <u><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id), class:"text-dark" %></u>
              </td>
              <td><%= order.name %></td>
              <td><%= order.order_items.to_a.sum { |order_item| order_item.quantity } %></td>
              <td><%= order.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <!--ここまでテーブル箇所-->
      <div class="pagenation">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%# admin/注文履歴詳細ページ %>
<div class="container">
  <div class="row">
    <h4 class="bg-light text-black px-4 offset-1">注文履歴詳細</h4>
  </div>
  <div class="row">
    <table class="table table-borderless">
      <tmain>
        <tr>
          <th class="col-2">購入者</th>
          <td><%= link_to @order.name, admin_customer_path(@order.id) %></td>
        </tr>
        <tr>
          <th class="col-2">注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class="col-2">配送先</th>
          <td>
            <%= @order.postcode %></br>
            <%= @order.address %></br>
            <%= @order.name %></br>
          </td>
        </tr>
        <tr>
          <th class="col-2">支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th class="col-2">注文ステータス</th>
          <td>
          <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
            <!--selectedで指定された値の選択肢が最初から選択された状態にする-->
            <!--Order.statuses[@order.status]でenumの元の値を取得する-->
            <%= f.select :status, @array_order_status, {selected: Order.statuses[@order.status]} %>
            <%= f.submit "更新", class:"btn btn-sm btn-info" %>
          <% end %>
          </td>
          <td></td>
        </tr>
      </tmain>
    </table>
  </div>

  <div class="row">
    <table class="table col-10">
      <thead class="thead-light">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.product.name %></td>
            <td><%= order_item.purchase_price %></td>
            <td><%= order_item.quantity %></td>
            <td><%= order_item.sub_total_price %></td>
            <td>
              <%= form_with model: order_item, url: admin_order_order_item_path(order_id: @order.id, id: order_item.id), method: :patch, local: true do |f| %>
              <!--selectedで指定された値の選択肢が最初から選択された状態にする-->
              <!--OrderItem.making_statuses[order_item.making_status]でenumの元の値を取得する-->
              <%= f.select :making_status, @array_order_item_making_status, {selected: OrderItem.making_statuses[order_item.making_status]} %>
              <%= f.submit "更新", class:"btn btn-sm btn-info" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table-sm table-borderless col-2">
      <tright>
        <tr>
          <td>商品合計</td>
          <td><%= @order.order_items.to_a.sum{ |item| item.sub_total_price } %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <th><%= @order.billing_total %></th>
        </tr>
      </tright>
    </table>
  </div>
</div>