config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # デバイス関連のルーティング
  ##########ここから##########
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  #admins/registrationsは必要？  registrations: 'admins/registrations'
  }

  ##########ここまで##########

  #管理者ページのルーティング
  ##########ここから##########
  namespace :admin do
    #admin/customersコントローラのルーティング
    resources :customers, only: [:index, :show, :edit, :update]

    #admin/productsコントローラのルーティング
    resources :products, only: [:index, :show, :edit, :new, :update, :create]

    #admin/genresコントローラのルーティング
    resources :genres, only: [:index, :edit, :update, :create]

    #admin/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :update] do

      #admin/order_itemsコントローラのルーティング
      resources :order_items, only: [:update]
    end
  end
  ##########ここまで##########

  #会員ページのルーティング
  ##########ここから##########
  scope module: :public do
    #public/homesコントローラのルーティング
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'

    #public/cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete 'cart_items', to: 'cart_items#destroy_all', as: 'destroy_all'


    #public/customersコントローラのルーティング
    get '/customers/mypage', to: 'customers#show', as: 'mypage'
    resource :customers, only: [:edit, :update] do
      collection do
        get 'quit_check'#'/customers/quit_check', to: 'customers#quit_check', as:
        patch 'quit'#'/customers/quit', to: 'customers#quit', as:
      end
    end

    #public/deliveriesコントローラのルーティング
    resources :deliveries, only: [:index, :edit, :update, :destroy]

    #public/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get 'finish'#'/orders/finish', to: 'orders#finish', as:
        post 'confirm'#'/orders/confirm', to: 'orders#confirm', as:
      end
    end

    # public/searchコントローラのルーティング
    get "/customers/search", to: "search#search", as: "search"

  devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  # passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
  }

    #public/productsコントローラのルーティング
    resources :products, only: [:index, :show]
  end
##########ここまで##########
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :product_image

  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :customers, through: :cart_items
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :description, presence: true
  validates :base_price, presence: true
  validates :product_image_id, presence: true
  validates :sale_status, presence: true

  # 商品の税込み価格を返すメソッド
  def price
    return (self.base_price * 1.08).floor
  end

  # 商品の税込価格を計算し、3桁毎に","で区切ったものを返す
  def tax_in_price
    floor_price = (base_price * 1.08).floor
    floor_price.to_s(:delimited, delimiter: ',')
  end

  # 商品の税抜価格を計算し、3桁毎に","で区切ったものを返す
  def no_tax_price
    floor_price = base_price.floor
    floor_price.to_s(:delimited, delimiter: ',')
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def create
    @product = Product.new(product_params)
    @genres = Genre.all
    if @product.save
      redirect_to admin_product_path(@product.id)
    else
      render action: :new
    end
  end

  private
  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :product_image,
      :genre_id,
      :base_price,
      :sale_status
    )
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
<%# admin/商品編集ページ %>

<%= form_with model: @product, url: admin_product_path(@product.id), method: :patch, local: true do |f| %>
<div class="container">
  <div class="row">
    <div class="col-12">
    <h4 class="col-2 offset-1 bg-light text-black">商品編集</h4>
    <table class="table table-borderless">
        <tr class="field">
          <th><%= f.label "商品画像" %></th>
          <td>
            <%= attachment_image_tag @product, :product_image, class:"col-12" %><br>
            <%= f.attachment_field :product_image, class:"mt-2" %>
          </td>
        </tr>
        <tr class="field">
          <th><%= f.label "商品名" %></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr class="field">
          <th><%= f.label "商品説明" %></th>
          <td><%= f.text_area :description, :size=>"23x5" %></td>
        </tr>
        <tr class="field">
          <th><%= f.label "ジャンル" %></th>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: @product.genre.id  %></td>
        </tr>
        <tr class="field">
          <th><%= f.label "税抜価格" %></th>
          <td><%= f.text_field :base_price %>円</td>
        </tr>
        <tr class="field">
          <th><%= f.label "販売ステータス" %></th>
            <td>
              <%= f.radio_button :sale_status, :true %>販売中
              <%= f.radio_button :sale_status, :false %>販売停止中
            </td>
        </tr>
        <tr>
          <td><%= f.submit "変更を保存", class: "btn btn-info" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/products/index.html.erb
<!--５ページ-->

<div class="container">
  <div class="row">
    <div class="mt-1 col-8">
     <h3>商品一覧</h3>
    </div>       <!--+ボタンは新規登録画面へ-->
    <div class="mb-3 col-3 text-right">
      <button type="button" class="btn btn-outline-info shadow-sm rounded-circle p-0" style="width:3rem;height:3rem;">
        <%= link_to "＋", new_admin_product_path %>
      </button>
    </div>

      <div class="col-10 mx-auto">
      <table class="table">
        <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td>
                <%= link_to admin_product_path(product.id) do %>
                  <%= product.name %>
                <% end %>
              </td>
              <td><%= product.no_tax_price %></td>
              <td><%= product.genre.name %></td>
              <td><% if product.sale_status == true %>
                  <p class="text-success">販売中</p>
                <% elsif product.sale_status == false %>
                  <p>販売停止中</p>
                <% end %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
       <%= paginate @products %>
    </div>



    </div>

  </div>

</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      
      <div>
        <h2>商品新規登録</h2>
      </div>
      <div>
        <%= form_with model: @product, url: admin_products_path, method: :post, local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group mt-3 row">
            <%= f.label "商品画像：", class:"col-2 col-form-label" %>
            <%= f.file_field :product_image %>
          </div>
          <div class="form-group row">
            <%= f.label "商品名：", class:"col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :name, class:"form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label "商品説明：", class:"col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_area :description, class:"form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label "ジャンル：", class:"col-2 col-form-label" %>
            <div class="col-10">
              <%= f.collection_select(:genre_id, @genres, :id, :name) %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label "税抜価格：", class:"col-2 col-form-label" %>
            <div class="col-10">
              <%= f.text_field :base_price, class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "販売ステータス：" %>
            <%= f.radio_button :sale_status, true %>販売中
            <%= f.radio_button :sale_status, false %>販売停止中
          </div>
          <div class="form-group">
            <%= f.submit "新規登録", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<!--6ページ-->
<div class="container">

  <h3>商品詳細</h3>

 <div class="row">
    <div class="col-md-5 product-detail-image mt-5">
          <!--<img width="100%" height="100%" src="/assets/no_image_kuma-d2885aa38b30459497e11dbe886eb75bf2fa379889bddc76542c03ab1a954d5d.jpg">-->
          <%= attachment_image_tag @product, :product_image, format: 'jpeg', fallback: 'no_image_kuma.jpg', size: "300x220" %>
    </div>

    <div class="mt-5 col-md-6">
      <table class="table">
        <tr>
          <td>商品名</td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @product.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格(税抜価格)</td>

          <!--.to_iは整数にするメソッド.to_s(:delimited)は３桁で区切るメソッド&nbsp;は半角スペース-->
          <td><%= ((@product.base_price*1.08).to_i).to_s(:delimited) %>&nbsp;(<%= (@product.base_price).to_s(:delimited) %>)円</td>

        </tr>
        <tr>
          <td>販売ステータス</td>
          <td><% if @product.sale_status == true %>
              <p>販売中</p>
              <% elsif @product.sale_status == false %>
              <p>販売停止中</p>
              <% end %>
          </td>
        </tr>
      </table>

        <%= link_to '編集する', edit_admin_product_path, class: 'btn btn-secondary btn-sm' %>

   </div>
  </div>
</div>