config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # デバイス関連のルーティング
  ##########ここから##########
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  #admins/registrationsは必要？  registrations: 'admins/registrations'
  }

  ##########ここまで##########

  #管理者ページのルーティング
  ##########ここから##########
  namespace :admin do
    #admin/customersコントローラのルーティング
    resources :customers, only: [:index, :show, :edit, :update]

    #admin/productsコントローラのルーティング
    resources :products, only: [:index, :show, :edit, :new, :update, :create]

    #admin/genresコントローラのルーティング
    resources :genres, only: [:index, :edit, :update, :create]

    #admin/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :update] do

      #admin/order_itemsコントローラのルーティング
      resources :order_items, only: [:update]
    end
  end
  ##########ここまで##########

  #会員ページのルーティング
  ##########ここから##########
  scope module: :public do
    #public/homesコントローラのルーティング
    root to: 'homes#top'
    get '/about', to: 'homes#about', as: 'about'

    #public/cart_itemsコントローラのルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete 'cart_items', to: 'cart_items#destroy_all', as: 'destroy_all'


    #public/customersコントローラのルーティング
    get '/customers/mypage', to: 'customers#show', as: 'mypage'
    resource :customers, only: [:edit, :update] do
      collection do
        get 'quit_check'#'/customers/quit_check', to: 'customers#quit_check', as:
        patch 'quit'#'/customers/quit', to: 'customers#quit', as:
      end
    end

    #public/deliveriesコントローラのルーティング
    resources :deliveries, only: [:index, :edit, :update, :destroy]

    #public/ordersコントローラのルーティング
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get 'finish'#'/orders/finish', to: 'orders#finish', as:
        post 'confirm'#'/orders/confirm', to: 'orders#confirm', as:
      end
    end

    # public/searchコントローラのルーティング
    get "/customers/search", to: "search#search", as: "search"

  devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  # passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
  }

    #public/productsコントローラのルーティング
    resources :products, only: [:index, :show]
  end
##########ここまで##########
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <title>Nagano Cake Official Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <!--ここからヘッダー-->
      <div class="navbar mb-3 py-4">
        <div class="navbar navbar-brand">
          <%= link_to root_path do %>
            <div class="header-menu">
              <img src="/assets/header/logo_off.png" alt="about">
            </div>
          <% end %>
          
          test
          
        </div>
        <div class="navbar">
          <% if admin_signed_in? %>
            <%= link_to "商品一覧", admin_products_path, class:"nav-menu-text m-2" %>
            <%= link_to "会員一覧", admin_customers_path, class:"nav-menu-text m-2" %>
            <%= link_to "注文履歴一覧", admin_orders_path, class:"nav-menu-text m-2" %>
            <%= link_to "ジャンル一覧", admin_genres_path, method: :get, class:"nav-menu-text m-2" %>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-menu-text m-2" %>
          <% elsif customer_signed_in? %>
            <div class="text-white p-2 mx-2">
              ようこそ 「<%= current_customer.last_name %> <%= current_customer.first_name %>」 様
            </div>
            <%= link_to "マイページ", mypage_path, class:"nav-menu-text m-2" %>
            <%= link_to "商品一覧", products_path, class:"nav-menu-text m-2" %>
            <%= link_to "カート", cart_items_path, class:"nav-menu-text m-2" %>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-menu-text m-2" %>
          <% else %>
            <%= link_to "about", about_path, class:"nav-menu-text m-2" %>
            <%= link_to "商品一覧", products_path, class:"nav-menu-text m-2" %>
            <%= link_to "新規登録", new_customer_registration_path, class:"nav-menu-text m-2" %>
            <%= link_to "ログイン", new_customer_session_path, class:"nav-menu-text m-2" %>
          <% end %>
        </div>
      </div>
    </header>
    <!--ここまでヘッダー-->

    <!--ここからapplication.html.erb内に "notice & alert" の呼び出しを追加-->
    <p class="notice ml-3 text-success"><%= notice %></p>
    <p class="alert ml-3 text-danger"><strong><%= alert %></strong></p>
    <!--ここまでapplication.html.erb内に "notice & alert" の呼び出しを追加-->

    <%= yield %>

    <!--ここからフッター-->
    <footer class="bg-dark p-5 mt-5">
      <div class="container">
        <div class="row">
          <div class="col-6 text-white">
            Nagano Cake<br>
            〒xxx-xxxx<br>
            長野県xxx市xxx0-00-0<br>
            Tel：<u><a href="tel:+81-90-0000-0000" class="text-white">090-0000-0000</a></u><br>
            Mail：<u><a href="mailto:address" class="text-white">info@nagano-cake.com</a></u><br>
            店舗営業時間：9:00 ~ 20:00<br>
            休業日：毎週水曜日<br>
          </div>
        </div>
      </div>
      <div>
        <div class="text-white text-center">©30 dogs</div>
      </div>
    </footer>
    <!--ここまでフッター-->
  </body>
</html>

app/views/layouts/test.html.erb
testtest